export const item = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة غدا",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "غدا",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "4.png",
  },
  {
    id: Math.random(),
    title: "وجبة غدا ممتاز",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "غدا",
    imgUrl: "5.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء درجه اولى",
    dascription: "وصف الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "6.png",
  },
];
